### ISSUE TITLE
RFE: support Ubuntu

### ISSUE THREAD

**Issue by ktdreyer** [junaruga/rpm-py-installer#131]
Travis CI environments are Ubuntu (containers) by default. It would be great to `pip install rpm-py-installer` in these environments directly.

Ubuntu has "rpm" available https://packages.ubuntu.com/source/bionic/rpm . However, when I `apt-get install rpm`, the rpmdb on Ubuntu contains no knowledge of any installed packages, so `rpm -q <anything>` will always fail. rpm-py-installer runs `rpm -q rpm-libs`, and this fails.

```
Collecting rpm-py-installer (from koji->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/4f/30/e3e6557eff7129fa1b415b957b45ccbbbc93f0dac2f247bb6d6d6eb5ca7a/rpm-py-installer-0.7.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/rpm_py_installer.egg-info
    writing pip-egg-info/rpm_py_installer.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/rpm_py_installer.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/rpm_py_installer.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    [INFO] Installing...
    Traceback (most recent call last):
      File "install.py", line 1336, in <module>
        main()
      File "install.py", line 1331, in main
        app.run()
      File "install.py", line 31, in run
        self._verify_system_status()
      File "install.py", line 129, in _verify_system_status
        self._verify_rpm_package_status()
      File "install.py", line 133, in _verify_rpm_package_status
        self.rpm.verify_packages_installed(['rpm-libs'])
      File "install.py", line 986, in verify_packages_installed
        raise InstallError(message)
    __main__.InstallError:
    Required RPM not installed: [rpm-libs].
    Install the RPM package.
```

A possible solution would be to skip this check in `_verify_system_status()` if the operating system environment is not RPM-based.

**Comment by junaruga** [comment]
> A possible solution would be to skip this check in _verify_system_status() if the operating system environment is not RPM-based

Maybe skipping the method `_verify_system_status()` is not enough.
I have to check the entire logic considering the Ubuntu environment.

**Comment by ktdreyer** [comment]
Thanks!

1. Ubuntu version: Travis CI's native containers are "trusty"
2. Path to RPM: `/usr/bin/rpm`
3. RPM version: 4.11.1
4. In Trusty, `python --version` prints Python 2.7.6, but Travis CI sets up its own Python version

**Comment by junaruga** [comment]
@ktdreyer okay. I will start to work from `trusty`. then `bionic`.

**Comment by junaruga** [comment]
@ktdreyer sorry for late. I will try to fix this at first until next Monday morning.

**Comment by ktdreyer** [comment]
No problem @junaruga

**Comment by junaruga** [comment]
Sorry I could not finish. But I will fix this task and the downloading issue as the highest priority on my private project.

**Comment by junaruga** [comment]
Started to support Ubuntu Trusty now. Not released yet. Just merged to master branch.
Right now on Ubuntu, there is a dependency `libpopt-dev` to build RPM Python binding.
I am going to try to remove the dependency with similar way that I did on Fedora.
https://github.com/junaruga/rpm-py-installer/issues/142

**Comment by junaruga** [comment]
@ktdreyer Today I released Ubuntu supporting new version `rpm-py-installer` 0.8.0.
https://pypi.org/project/rpm-py-installer/0.8.0/

The top page is still 0.7.1, but you can download the 0.8.0 by `pip install rpm-py-installer`.
https://pypi.org/project/rpm-py-installer

I added Ubuntu trusty and bionic to Travis CI test case.

I would close this ticket.
But feel free to reopen if you have a issue, or want to ask me.

Cheers,
Jun
