### ISSUE TITLE
Can't install via /usr/bin/pipx.y when there's no pythonxy-rpm

### ISSUE THREAD

**Issue by jpopelka** [junaruga/rpm-py-installer#174]
```
$ docker run -ti centos:7 bash
# yum -y install epel-release
# yum -y install rpm-build python36-pip gcc python36-devel
# pip3.6 install rpm-py-installer
Collecting rpm-py-installer
    [INFO] Installing...
    Traceback (most recent call last):
    __main__.InstallError:
    RPM Python binding on system Python should be installed manually.
    Install the proper RPM package of python{,2,3}-rpm.
```

Now I can't install the RPM bindings, because `pip3.6 install rpm-py-installer` tells me to install `python36-rpm`, but there is no such RPM package.

The same applies to
- `python3.6 -m ensurepip` && `pip3.6 install rpm-py-installer`
- `yum install python34-pip` && `pip3.4 install rpm-py-installer`

**Comment by junaruga** [comment]
I think `rpm-py-installer` should provide an option to install the RPM Python binding to system.

**Comment by junaruga** [comment]
I merged the fix to the master branch.
You need to set a environment variable `RPM_PY_SYS=true`
Below workflow or `python3.6 -m ensurepip` should work on CentOS7.

```
# yum install python36 python36-devel python36-pip

# RPM_PY_SYS=true python36 -c "$(curl -fsSL https://raw.githubusercontent.com/junaruga/rpm-py-installer/master/install.py)"

# python36 -c "import rpm; print(rpm.__version__)"
4.11.3
```

Ideally the situation that there is no proper RPM package such as `python3-rpm` or `python36-rpm` should be detected automatically without the environment variable.
But it is next phase.

Thank you for the reporting.
Please wait next release to use it from `pip install rpm-py-installer`.

**Comment by jpopelka** [comment]
Works OK, thank you!

**Comment by junaruga** [comment]
@jpopelka Now I released the new version!
