### ISSUE TITLE
Supporting both podman and docker for docker-compose.yml

### ISSUE THREAD

**Issue by junaruga** [junaruga/rpm-py-installer#193]
To have more flexibility for the build, try to unify the logic with `Makefile` and shell script as an experiment.

Stop using `docker-compose.yml`.

Because
* We can not use `variable` in the file.
* We want to support both `podman` and `docker` for the accessibility from developers, and show multiarch test cases with reproductive ways to people as much as possible.

In `Makefile`, if `podman` is installed, set `podman` to `DOCKER`, otherwise set `docker` to `DOCKER`.
For how to install `podman`, maybe I can refer below case.
https://github.com/junaruga/multiarch-rhel-experiment/blob/master/.travis.yml

```
- sourceline: 'ppa:projectatomic/ppa'
```

**Comment by dcermak** [comment]
How about [podman-compose](https://github.com/containers/podman-compose) instead 😉?

**Comment by junaruga** [comment]
Yeah, that's good idea. Right now I am waiting this ticket will be fixed to run podman on Travis CI.
https://github.com/containers/libpod/issues/3679

**Comment by junaruga** [comment]
It's good to watch ubuntu tags in podman issues page.
https://github.com/containers/libpod/issues?q=is%3Aissue+is%3Aopen+label%3Aubuntu

**Comment by junaruga** [comment]
As the repository supports both podman and docker removing `docker-compose.yml` by #229 and #231, I would close the issue ticket. I think removing `docker-compose` dependency simplifies the development workflow.
