### ISSUE TITLE
Releasing the new version 1.2.0

### ISSUE THREAD

**Issue by junaruga** [junaruga/rpm-py-installer#253]
This issue ticket is to manage the new version release.

I checked the current diff from the previous release v1.1.0

```
$ git diff --name-only v1.1.0..HEAD
.github/workflows/build-and-test.yml
.github/workflows/matrix_includes.json
.travis.yml
README.md
ci/Dockerfile-centos
ci/Dockerfile-centos.6
ci/Dockerfile-centos.7
ci/Dockerfile-fedora
ci/Dockerfile-opensuse
ci/Dockerfile-ubuntu.trusty
ci/install_podman_on_ubuntu.sh
docs/developers_guide.md
install.py
setup.py
test-cov-requirements.txt
test-lint-requirements.txt
test-requirements.txt
tests/conftest.py
tests/test_install.py
tests/test_install_fedora.py
tests/test_install_suse.py
tox-py34-requirements.txt
tox-requirements.txt
tox.ini
```

The related logic files are below in the file list. I can see there are only bug fixes, and no new feature. So, I want to release the new version as version 1.1.1 increasing the maintenance version.

```
$ git diff v1.1.0..HEAD install.py setup.py
...<snip>...
```

@nforro I sent the invitation email to be the maintainer of the PyPI package.
https://pypi.org/project/rpm-py-installer/

If you don't mind, I would like you to try to release it this time. Here are the steps.
https://github.com/junaruga/rpm-py-installer/blob/master/docs/developers_guide.md#releasing

Before that, I want to update the `setup.py` a little bit.

**Comment by nforro** [comment]
Just a question, is there a reason not to use releases here on GitHub? PyPI publishing could be automated (example: https://github.com/packit/specfile/blob/52b30d03ca66c4d96b79fb57e6df5e4b6ed7fee9/.github/workflows/pypi-publish.yml).

**Comment by junaruga** [comment]
I don't have any reason not to use the publishing on GitHub Actions. Just I didn't know that. The contribution for that is welcome!

**Comment by junaruga** [comment]
> Before that, I want to update the setup.py a little bit.

As I want to change the `setup.py` adding (and maybe dropping) Python versions, the 1.2.0 is better than 1.1.1.

**Comment by nforro** [comment]
The "publish" action could be actually triggered even by pushing a new tag: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-of-specific-tags-occurs

So I suppose if there is no changelog or something that we would want to showcase, using only tags and not releases is fine.

**Comment by junaruga** [comment]
OK. There is no changelog or something for the rpm-py-installer.

**Comment by junaruga** [comment]
Note that here are the current tag info.

```
$ git tag -n
v0.1.1          v0.1.1 release
v0.1.2          v0.1.2 release
v0.1.3          v0.1.3 release
v0.2.0          v0.2.0 release
v0.3.0          v0.3.0 release
v0.3.1          v0.3.1 release
v0.4.0          v0.4.0 release
v0.4.1          v0.4.1 release
v0.4.2          v0.4.2 release
v0.5.0          v0.5.0 release
v0.5.0.dev1     v0.5.0.dev1 release
v0.6.0          v0.6.0 release
v0.6.1          v0.6.1 release
v0.7.0          v0.7.0 release
v0.7.1          v0.7.1 release
v0.8.0          v0.8.0 release
v0.8.1          v0.8.1 release
v0.9.0          v0.9.0 release
v0.9.1          v0.9.1 release
v0.9.2          v0.9.2 release
v1.0.0          v1.0.0 release
v1.1.0          v1.1.0 release
```

**Comment by junaruga** [comment]
@nforro , I updated the `setup.py` by https://github.com/junaruga/rpm-py-installer/commit/2fce9e904f4d571d3ef3323500ee9c523ecdabd1 . I think we are ready to release the new version 1.2.0. Could you try to release it when you have?

**Comment by nforro** [comment]
Ok, will do.

**Comment by nforro** [comment]
Ok, I pushed the tag: https://github.com/junaruga/rpm-py-installer/releases/tag/v1.2.0

But the `publish` action failed because `bdist_wheel` is not supported, so I have to either do it manually or fix it and bump release.
Here is a fix: https://github.com/junaruga/rpm-py-installer/pull/258

**Comment by nforro** [comment]
I published it on PyPI manually: https://pypi.org/project/rpm-py-installer/1.2.0/

**Comment by junaruga** [comment]
Thanks!!

One note, I see the tag's note is different unlike the past tags. Is it intentional?

```
$ git tag -n | tail -3
v1.0.0          v1.0.0 release
v1.1.0          v1.1.0 release
v1.2.0          Bump version
```

I installed the rpm-py-installer 1.2.0 on my local. I see that it works!

**Comment by nforro** [comment]
> One note, I see the tag's note is different unlike the past tags. Is it intentional?

Sorry, I didn't set a note when creating the tag and it picked up the corresponding commit message.

**Comment by junaruga** [comment]
Oh okay. It's okay. Thanks!
