### ISSUE TITLE
Install error on CentOS6, rpm: 4.8.0

### ISSUE THREAD

**Issue by junaruga** [junaruga/rpm-py-installer#86]
The detail is here.
https://github.com/junaruga/rpm-py-installer/pull/84#issuecomment-334172667
That is because RPM package `rpm-build-libs` does not exist on the old version.

Check the sub package and the so files' status of `rpm-libs` and `rpm-build-libs` from rpm v4.8.0.

**Comment by junaruga** [comment]
I will fix this later on maybe more than v0.5.1 or v0.6.0.

**Comment by junaruga** [comment]
if you like this issue fixed, let me know in this page.
Because I am not sure how many people need it is fixed.

**Comment by rohanpm** [comment]
It would be useful for me.

**Comment by junaruga** [comment]
@rohanpm okay, now it's time to fix this issue, and support CentOS6 and the old version RPM.

**Comment by hron84** [comment]
I got this:

```
root@ns03 [~]# rpm --version
RPM version 4.8.0
root@ns03 [~]# /opt/rh/python27/root/usr/bin/pip2.7 install rpm-py-installer
Collecting rpm-py-installer
  Downloading rpm-py-installer-0.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/rpm_py_installer.egg-info
    writing pip-egg-info/rpm_py_installer.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/rpm_py_installer.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/rpm_py_installer.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    Loaded plugins: fastestmirror
    Loading mirror speeds from cached hostfile
     * cpanel-addons-production-feed: 185.53.12.144
     * base: ftp.bme.hu
     * extras: ftp.bme.hu
     * updates: ftp.bme.hu
    No Match for argument rpm-build-libs.x86_64
    Nothing to download
    [INFO] Installing...
    [INFO] Created working directory '/tmp/tmpBkJMfo-rpm-py-installer'
    [INFO] Downloading archive. 'http://ftp.rpm.org/releases/rpm-4.8.x/rpm-4.8.0.tar.gz'.
    [INFO] Archive not found. URL: http://ftp.rpm.org/releases/rpm-4.8.x/rpm-4.8.0.tar.gz
    [INFO] Try to download next candidate URL.
    [INFO] Downloading archive. 'https://github.com/rpm-software-management/rpm/archive/rpm-4.8.0-release.tar.gz'.
    Traceback (most recent call last):
      File "install.py", line 1152, in <module>
        main()
      File "install.py", line 1147, in main
        app.run()
      File "install.py", line 38, in run
        self.rpm_py.download_and_install()
      File "install.py", line 173, in download_and_install
        self.installer.run()
      File "install.py", line 557, in run
        raise InstallError(message)
    __main__.InstallError:
    Install failed without rpm-devel package by below reason.
    Can you install the RPM package, and run this installer again?
    CMD: [yumdownloader rpm-build-libs.x86_64], Return Code: [1] at [/tmp/tmpBkJMfo-rpm-py-installer/rpm-rpm-4.8.0-release/python] Stderr: []
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-UH6sPI/rpm-py-installer/setup.py", line 128, in <module>
        'bdist_wheel': BdistWheelCommand,
      File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-UH6sPI/rpm-py-installer/setup.py", line 57, in run
        install_rpm_py()
      File "/tmp/pip-build-UH6sPI/rpm-py-installer/setup.py", line 20, in install_rpm_py
        raise Exception('Command failed: {0}'.format(cmd))
    Exception: Command failed: /opt/rh/python27/root/usr/bin/python2 install.py
    
    ----------------------------------------
```

**Comment by junaruga** [comment]
@hron84 Thanks for contacting me.
Yes, `rpm-py-installer` does not work in RPM 4.8.0.
I want to fix it.
But right now I have no time, as I am busy for other tasks.
Is it urgent for you? When do you want this to be fixed until?

Or someone do you want to fix this?
It is good to fix this issue, adding CentOS6 (CentOS6 docker is using RPM 4.8.0) to Travis CI.
https://github.com/junaruga/rpm-py-installer/pull/84

**Comment by junaruga** [comment]
I decided that I will try to fix until next Monday December 12.
Please want a moment :)

**Comment by hron84** [comment]
@junaruga December is 11 months ahead or 1 month back. Can I assume you meant 12 January? 😄 

Otherwise: the fix is not as urgent, but I try to automate some old CloudLinux servers that I cannot upgrade atm. Ansible however does not like the installed 2.6.6 Python as `os.chmod` does not work well with this interpreter. I experimenting with custom Python (SCL/cPanel Pythons) but I would like to use `yum` Ansible module which is needs `rpm` Python module.

**Comment by junaruga** [comment]
> @junaruga December is 11 months ahead or 1 month back. Can I assume you meant 12 January? 

Haha, sorry it's not December but February.
OK. I understand your situation.

I try to fix until next Monday February 12th.

**Comment by hron84** [comment]
Yeah, I mistyped it too. Months changes without any notification. It demands a service. :D

**Comment by junaruga** [comment]
I tried this weekend. I proceeded it.
But the issue is still not fixed.

You can install the RPM Python bindings on CentOS6, and rpm-4.8.0.
But I must face the runtime error, when running the Python binding.

The situation is `setup.py.in` for the python bindings was created at 4.10.0 at first time.
Until the version, there was the python binding without `setup.py.in` file.

I prepared own `setup.py.in` for 4.8.0 right now to build it.

I also implemented a feature that `rpm-py-installer` can patch some patch files from such s `rpm_py_installer/data/patches/4.8.x/*.patch`.
But maybe I need more patches to fix it.

```
$ git clone https://github.com/junaruga/rpm-py-installer.git

$ git checkout feature/add-centos6-test

$ RPM_PY_VERBOSE=true RPM_PY_WORK_DIR_REMOVED=false python install.py

$ cd ..

$ python -m pip list (or pip list)
pip (8.1.1)
rpm-python (4.8.0)
setuptools (20.10.1)

$ cd ..

$ python -c "import rpm; print(rpm.__version__)"
  => runtime error.
```

I will proceed, and might think better approach to fix it.

**Comment by junaruga** [comment]
I am working in https://github.com/junaruga/rpm-py-installer/pull/84 .

**Comment by junaruga** [comment]
@hron84 

> yum Ansible module which is needs rpm Python module.

By the way, what is "yum Ansible module"?
Could you tell the source URL?

**Comment by junaruga** [comment]
One more thing I want to share is that I was success to build RPM from source on CentOS6.
I needed to do it to check the behavior.
See http://junaruga.hatenablog.com/entry/2018/02/11/013608 for detail.

**Comment by junaruga** [comment]
I got an another good approach to fix this issue. Just moment for a short time.

**Comment by junaruga** [comment]
@hron84 okay, thanks for the info. The link that you introduced is good enough to know it.

**Comment by junaruga** [comment]
@tkdchen @rohanpm @hron84 

Fixed by https://github.com/junaruga/rpm-py-installer/pull/84 .

Now `rpm-py-installer` supports rpm v4.8.0 and CentOS 6.

Wait next version release of `rpm-py-installer` to use it by pip command. Today I will do it.
Or you can try directly right now.
Take note installed `rpm` (<= 4.8.x) is NOT listed in the result of `pip list`.
See below my test on CentOS6 for detail.

```
(venv2)[root@b5142f6aec58 work]# pip list
You are using pip version 6.0.8, however version 10.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
pip (6.0.8)
setuptools (12.0.5)

(venv2)[root@b5142f6aec58 work]# python --version
Python 2.6.6

(venv2)[root@b5142f6aec58 work]# python -c "$(curl -fsSL https://raw.githubusercontent.com/junaruga/rpm-py-installer/master/install.py)"

[INFO] Done successfully.

(venv2)[root@b5142f6aec58 work]# pip list
You are using pip version 6.0.8, however version 10.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
pip (6.0.8)
setuptools (12.0.5)

[root@b5142f6aec58 work]# ls venv2/lib/python2.6/site-packages/rpm/
__init__.py   __init__.pyo    _rpmmodule.so   transaction.pyc
__init__.pyc  _rpmbmodule.so  transaction.py  transaction.pyo

(venv2)[root@b5142f6aec58 work]# python -c 'import rpm; print(rpm.ts)'
<class 'rpm.transaction.TransactionSet'>
```

**Comment by junaruga** [comment]
You can reopen if you need anytime.

**Comment by junaruga** [comment]
@tkdchen @rohanpm @hron84

I released `rpm-py-installer` v0.7.0 to pypi right now.
Thank you for waiting patiently for 6 months and 14 days for this issue.
It was a long journey.

**Comment by jasonaw79** [comment]
Is it possible to to install the rpm-python on Python3?

**Comment by junaruga** [comment]
@jasonaw79 You mean the `rpm-python` 4.8.0 on Python3 on CentOS 6? As far as I know, the `rpm-python` RPM provided by CentOS 6 is built on Python 2, not Python 3. There is no RPM Python binding RPM built on Python 3 on CentOS 6. And I have not consider the case. The current CI config file `.travis.yml` does not have the case on Python 3 on CentOS 6. I am not sure if it is possible. If you have some logs, you can open a new issue ticket for that.
