### ISSUE TITLE
How is rpm-py-installer version mapped to python[23]-rpm version? 

### ISSUE THREAD

**Issue by tkdchen** [junaruga/rpm-py-installer#94]
As per title. Thanks.

**Comment by junaruga** [comment]
The version mapping's default behavior is to use same version with the system RPM's version on local.

`rpm-py-installer` gets the RPM version from a command `rpm --version` by below command, and build and install the version's Python binding from the source on local.

`rpm-py-installer` do not see the RPM packages `python[23]-rpm`.

## For detail.

1. Get the version string.

  ```
  $ rpm --version
  RPM version N.N.N.N (Version string)
  ```

2. Get the target archive tar.gz file from https://github.com/rpm-software-management/rpm/releases , or get source by `git clone && git checkout tag or branch`.

3. Patching `setup.py.in` into `setup.py`.
https://github.com/rpm-software-management/rpm/blob/master/python/setup.py.in

4. Build and install the Python binding by the file.


## Specifying the Python binding version

Install the version 4.14.0

```
$ RPM_PY_VERSION=4.14.0 pip install rpm-py-installer
```

Install from the edge of `rpm-4.14.x` branch in the `rpm` repository (https://github.com/rpm-software-management/rpm).

```
$ GIT_BRANCH=rpm-4.14.x pip install rpm-py-installer
```

**Comment by tkdchen** [comment]
Thank you very much.

**Comment by junaruga** [comment]
@tkdchen welcome! Which Python package are you trying to adapt `rpm-py-installer` for?
I have a curiosity for that.

**Comment by tkdchen** [comment]
It's rpkg. I opened a PR to add rpm-py-installer to it so that rpkg could be installed from PyPI one day, and that change would be easier to provision environment to run tests.
