### ISSUE TITLE
Assisting rpkg in PyPI

### ISSUE THREAD

**Issue by junaruga** [junaruga/rpm-py-installer#97]
From this conversation: https://github.com/junaruga/rpm-py-installer/issues/94#issuecomment-340948266

@tkdchen If you have requests to me related to `rpkg`, feel free to ask me.

Maybe the issue and PR page in `rpkg` are here.
https://pagure.io/rpkg/issue/224
https://pagure.io/rpkg/pull-request/261

**Comment by tkdchen** [comment]
Thank you. Both of these links are related and can benefit from rpm-py-installer.

**Comment by junaruga** [comment]
@tkdchen 

I found `rpkg` was using `rpm-py-installer`.
https://pagure.io/rpkg/blob/master/f/requirements/pypi.txt#_10

Do you like still opening this ticket?

By the way, `rpm-py-installer` started to support CentOS6 and rpm version 4.8.0.
You can try it :)

**Comment by tkdchen** [comment]
@junaruga This issue can be closed. Thanks for your great work.

**Comment by junaruga** [comment]
@tkdchen okay! :smiley:
